#!/usr/bin/env bash
# Build the ark-429-autoban CPA plugin using the pre-built builder image.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="${PROJECT_DIR}/dist"
IMAGE="429builder:latest"
OUTPUT="${OUTPUT_DIR}/ark-429-autoban.so"

mkdir -p "$OUTPUT_DIR"

echo "Compiling ark-429-autoban.so using $IMAGE..."
docker run --rm \
  -e GOPROXY=https://goproxy.cn,direct \
  -e GOFLAGS=-mod=mod \
  -v "$PROJECT_DIR":/build:ro \
  -v "$OUTPUT_DIR":/out \
  --entrypoint sh \
  "$IMAGE" \
  -c 'cd /build && CGO_ENABLED=1 go build -buildmode=c-shared -ldflags="-s -w" -o /out/ark-429-autoban.so ./cmd/ark-429-autoban && echo BUILD_OK'

# The C header is generated by c-shared but CPA only loads the shared object.
rm -f "${OUTPUT_DIR}/ark-429-autoban.h"

echo
echo "Done: $OUTPUT"
